name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job triggered by a ${{ github.event_name }} event."
      - run: echo "job is running on a ${{ runner.os }} server"
      - run: echo "branch name is ${{ github.ref }}"
      - name: Check out repo code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} was cloned."
      - run: echo "The workflow is ready for testing"
      - name: List files in repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "job status is ${{ job.status }}"
